### ISSUE TITLE
Undefined names in code

### ISSUE THREAD

**Issue by goodmami** [nltk/wordnet#22]
I noticed that WordNetError was not imported in some modules that raised it. For instance:

```python-console
>>> import wn
>>> w = wn.WordNet()
>>> next(w.words())
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/home/goodmami/postdoc/wnsd/env/lib/python3.8/site-packages/wn/__init__.py", line 189, in all_lemma_names
    self._load_lang_data(lang)
  File "/home/goodmami/postdoc/wnsd/env/lib/python3.8/site-packages/wn/omw.py", line 79, in _load_lang_data
    raise WordNetError("Language is not supported.")
NameError: name 'WordNetError' is not defined
```

Running Flake8 to look for [F821](https://www.flake8rules.com/rules/F821.html) finds that this happens in `wn/omw.py` and `wn/constants.py`. There are also many other things undefined:

```console
$ flake8 wn --select F821
wn/reader.py:38:34: F821 undefined name '_lemma_pos_offset_map'
wn/reader.py:79:15: F821 undefined name '_lemma_pos_offset_map'
wn/reader.py:183:18: F821 undefined name '_lemma_pos_offset_map'
wn/reader.py:188:24: F821 undefined name '_lemma_pos_offset_map'
wn/reader.py:197:37: F821 undefined name '_synset_offset_cache'
wn/reader.py:205:39: F821 undefined name '_synset_offset_cache'
wn/reader.py:222:55: F821 undefined name 'line'
wn/omw.py:33:19: F821 undefined name 'WordNetError'
wn/omw.py:47:19: F821 undefined name 'WordNetError'
wn/omw.py:75:20: F821 undefined name '_lang_to_lemmas_to_offsets'
wn/omw.py:76:24: F821 undefined name '_lang_to_offsets_to_lemma'
wn/omw.py:79:19: F821 undefined name 'WordNetError'
wn/omw.py:82:9: F821 undefined name '_lang_to_offsets_to_lemma'
wn/omw.py:83:9: F821 undefined name '_lang_to_lemmas_to_offsets'
wn/constants.py:175:27: F821 undefined name 'WordNetError'
wn/info.py:51:20: F821 undefined name '_INF'
wn/info.py:123:20: F821 undefined name '_INF'
wn/info.py:135:20: F821 undefined name '_INF'
wn/path.py:22:5: F821 undefined name 'max_depth'
wn/path.py:22:16: F821 undefined name 'min_depth'
wn/lemma.py:31:28: F821 undefined name '_synset_offset_cache'
wn/lemma.py:47:18: F821 undefined name '_synset_offset_cache'
wn/lemma.py:64:32: F821 undefined name '_lemmakey_to_count'
wn/lemma.py:67:27: F821 undefined name '_lemmakey_to_count'
wn/lemma.py:102:13: F821 undefined name '_synset_offset_cache'
```

**Comment by alvations** [comment]
As for the OMW part, I think there's a missing import to https://github.com/nltk/wordnet/blob/master/wn/utils.py#L15 at https://github.com/nltk/wordnet/blob/master/wn/omw.py#L12 . There should be a 

```
from wn.utils import WordNetError
``` 

The flake complains are because of all the global hacks done to keep those variables like how they used to be in `nltk.corpus.wordnet`. This is a little nasty to fix.

**Comment by goodmami** [comment]
> The flake complains are because of all the global hacks done to keep those variables like how they used to be in `nltk.corpus.wordnet`. This is a little nasty to fix.

Is it a goal for even the non-public API to be compatible with NLTK? I'd like to think we can get rid of these hacks and make the package simpler. Even better is if we could break compatibility to improve the API, but that's another issue.

**Comment by alvations** [comment]
For now, I think the current version serves the purpose of resolving https://github.com/nltk/nltk/issues/2266 and some other bugs tagged with `wordnet` on https://github.com/nltk/nltk

But I agree, a redesign of the whole API would have been much better =)

**Comment by goodmami** [comment]
I see. Thanks for the context.

**Comment by goodmami** [comment]
> But I agree, a redesign of the whole API would have been much better =)

That has now been [done](https://github.com/goodmami/wn/) :)

I'll close this issue.
