### ISSUE TITLE
Wordnet 3.1 is called 3.3 here

### ISSUE THREAD

**Issue by goodmami** [nltk/wordnet#25]
The directory `wn/data/wordnet-3.3` should be `wn/data/wordnet-3.1`, assuming it is 3.1 data. 3.3 is not yet released (or 3.2 for that matter).

**Comment by alvations** [comment]
Yes, that was the confusion I had =)

https://github.com/globalwordnet/english-wordnet was labeled 3.3 so I was thinking it's princeton wn 3.3 but now I understand that it's different. 

Renaming the directories in the coming version.

**Comment by goodmami** [comment]
I'm going to close this as I don't think it will be fixed.

I'll note that PWN 3.1 is available as a WN-LMF file, and is indexed by https://github.com/goodmami/wn/:

```pycon
>>> import wn
>>> wn.download('pwn:3.1')
Download [###############################] (10048872/10048872 bytes) Complete
Added pwn:3.1 (Princeton WordNet 3.1)
```
