### ISSUE TITLE
Handling quotes in definitions

### ISSUE THREAD

**Issue by mufeedali** [nltk/wordnet#27]
WordNet has several words like `weird` that give quotes from famous authors, philosophers, etc as examples. `wn.WordNet` handles these cases poorly. This is evident in both adjective synsets of the word `weird` (`Synset('eldritch.s.01')` and `Synset('weird.s.02')`).

This is the definition of the first adjective synset according to the WordNet Python module: 
```
suggesting the operation of supernatural influences; ; ; - John Galsworthy; ; - Henry Kingsley
```

Here, `; ; ; - John Galsworthy; ; - Henry Kingsley` is not actually part of the definition, the two names are citations for the quotes in the examples. Furthermore, the examples lack the citation that should be a part of it.

A quick, obvious workaround would've been what I did in https://github.com/fushinari/wordnet/commit/0fad9b99c0283618f7165a907441438736aad650 but that would only fix the examples and would result in changing the behavior of `examples` from returning a list of strings to returning a list of tuples with 3 strings each.

It still doesn't fix the definitions and even breaks for some examples, as is evident if you try the fix with the second adjective synset of `weird`. Here, my regex will fail to capture the example if ran in Python. It does work well on non-Python regex search tools though, so I'm not sure why it fails. (presence of `;` in the example?)

Thanks

**Comment by goodmami** [comment]
This is a data problem with the Princeton WordNet. The newer [English WordNet](https://github.com/globalwordnet/english-wordnet) lists the examples separately (here using the https://github.com/goodmami/wn/ library):

```pycon
>>> import wn
>>> eldritch = wn.synsets('eldritch', lexicon='ewn:2020')[0]
>>> eldritch.definition()
'suggesting the operation of supernatural influences'
>>> eldritch.examples()
['"an eldritch screech"', '"the three weird sisters"', '"stumps...had uncanny shapes as of monstrous creatures"- John Galsworthy', '"an unearthly light"', '"he could hear the unearthly scream of some curlew piercing the din"- Henry Kingsley']
```
