### ISSUE TITLE
Not able to access the wordnet resource

### ISSUE THREAD

**Issue by limewif** [nltk/wordnet#31]
I am not able to access wordnet resource hosted by NLTK. I am facing the following error:

```
>>> import nltk
>>> nltk.download('wordnet')
[nltk_data] Error loading wordnet: <urlopen error [WinError 10060] A
[nltk_data]     connection attempt failed because the connected party
[nltk_data]     did not properly respond after a period of time, or
[nltk_data]     established connection failed because connected host
[nltk_data]     has failed to respond>
```
NLTK version:3.6.7
Python version: 3.8.13
Tried out various solutions like changing network, looking out for proxy connections, turning off firewall, etc. Still I am not able to resolve it.

**Comment by goodmami** [comment]
@limewif thanks for the notice but (a) this is an issue for the NLTK (and it looks like you've already created one there: https://github.com/nltk/nltk/issues/3075), and (b) this repo is no longer maintained. I'm going to close this issue.
